server:
  port: 8070
  servlet:
    context-path: /
     

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          kangLu-master1: # 主数据源
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/jtdb
            username: root
            password: 123456
          kangLu-master2: # 主数据源
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:oracle:thin:@localhost:1521:ORCL
            username: scott
            password: kang    
        
        
        
        
    rabbitmq:
        host: 192.168.2.7
        port: 5672
        virtualHost: /pd
        username: admin
        password: admin  
#        listener:
#          simple:
#            acknowledge-mode: manual
#          direct:
#            acknowledge-mode: manual 
            
#            spring.rabbitmq.listener.direct.acknowledge-mode=manual
#            spring.rabbitmq.listener.simple.acknowledge-mode=manual

#mybatis:
#  typeAliasesPackage: cn.tedu.pojo
#  mapperLocations: classpath:mybatis/mappers/*.xml
  
#mybatis-plush配置
mybatis-plus:
  #定义别名包
  type-aliases-package: cn.tedu.pojo
  mapper-locations: classpath:mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
  
  
  

logging:
  level: 
    cn.tedu.mapper: debug